### ISSUE TITLE
Errors when running Cron

### ISSUE THREAD

**Issue by davidbarratt** [mediamosa/mediamosa-sdk#9]
When running cron via Drush, we recieve the follow set of errors many times:
```
Invalid error type specified mediamosa_connector.response.class.inc:76                                                                                                                                   [warning]
WD mediamosa: Connector request to asset/create was malformed. API path does not exist or failed to respond.                                                                                             [error]
WD mediamosa: Asset creation for file id 978923 failed.
```
This might be related to a [Feeds](https://www.drupal.org/project/feeds) Import, unless there is something else going on.

This causes a lot of images to not be rendered on the site properly.

**Comment by davidbarratt** [comment]
I'm using version `3.0.0`

**Comment by rblanker** [comment]
If asset/create is also used by the feeds module, then you have to separate the REST interface from the Drupal main url on your MediaMosa backend host (if feeds is running there as well). You can do this by adding a subdomain specially for the REST interface (something like app.mediamosa.[domain] and add a sitemap to /sites dir with the domain name (its basic Drupal multisite). Copy the example.settings.php from app1.mediamosa.local to settings.php. The in the main settings.php under /sites/default, put 
$conf['mediamosa_app'] = FALSE;
That will disable most REST calls (like /asset/create). Some REST calls will still be available, the REST call related to upload and download.

If asset/create is not used by feeds module or if this does not help, let me know.

3.0.0? SDK? Take the latest 3.6 on github, although its still dev, it should work fine and better with older front ends. May I know what version MM backend you are using or connecting to?

**Comment by davidbarratt** [comment]
MediaMosa v3.2.2 (build 1882)
